### ISSUE TITLE
OS X install database issue

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/ISCAN#186]
Not sure if this should go iscan-spade-server issues?

I managed to install iscan-spade-server on my OS X laptop (!), via Docker install.  So now I am trying to import a first corpus, which I have put in the `polyglot_source` directory.  The page for the database to load looks normal:

<img width="1170" alt="Screen Shot 2019-04-08 at 5 10 34 PM" src="https://user-images.githubusercontent.com/798417/55735262-4801aa00-5a21-11e9-93b7-23492e132489.png">

but then if I click "Start", it just cycles quickly from "Starting" back to "Start".  The trace from docker, starting from (I think) where I copied the corpus ("spade-tutorial") into the `polyglot_source` directory, is:

```
ps-app              | [08/Apr/2019 15:02:34] "GET /api/databases/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:02:51] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:03:01] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:03:12] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:03:23] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:03:34] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:03:45] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:04:00] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:04:11] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:04:22] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:04:33] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:04:44] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:04:55] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:05:06] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:05:17] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:05:28] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:05:43] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:05:54] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:06:05] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:06:16] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | [08/Apr/2019 15:06:18] "GET / HTTP/1.1" 200 7438
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/js/howler.min.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/css/app.css HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/env.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/css/plots.css HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/databases/databases.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/users/users.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/js/dsp.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/iscan.module.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/users/users.service.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/databases/databases.service.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/corpora/corpora.service.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/corpora/corpora.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/auth/auth.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/auth/validate.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/auth/auth.service.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/auth/auth.directives.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/database-list/database-list.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/database-detail/database-detail.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/query/query.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/enrichment.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/pitch_tracks/pitch_tracks.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/formant_tracks/formant_tracks.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/intensity_tracks/intensity_tracks.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/formant_points/formant_points.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/praat_script/praat_script.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/csv-properties/csv-properties.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/annotation-level/pause.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/annotation-level/utterance.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/annotation-level/syllable.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/stress-word-prop/stress-word-prop.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/relativization/relativization.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/subset/subset.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/vot/vot.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/enrichment/hierarchical/hierarchical.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/corpus-detail/corpus-detail.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/navbar/navbar.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/login/login.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/logout/logout.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/query/query.service.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/query/query.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/query/query.directives.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/enrichment/enrichment.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/enrichment/enrichment.service.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/annotations/annotations.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/components/annotations/annotations.service.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/intonation/bestiary-plot/bestiary-plot.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/intonation/components/query/intonation.query.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/intonation/components/query/intonation.query.service.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/intonation/components/query/intonation.query.directives.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:18] "GET /static/iscan/query-detail/query-detail.js HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:19] "GET /static/iscan/navbar/navbar.html HTTP/1.1" 304 0
ps-app              | [08/Apr/2019 15:06:19] "GET /api/rest-auth/user/ HTTP/1.1" 200 98
ps-app              | [08/Apr/2019 15:06:19] "GET /api/users/current_user/ HTTP/1.1" 200 103
ps-app              | [08/Apr/2019 15:06:19] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | Internal Server Error: /api/corpora/
ps-app              | Traceback (most recent call last):
ps-app              |   File "/site/env/lib/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
ps-app              |     return self.get(**kwargs), False
ps-app              |   File "/site/env/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
ps-app              |     self.model._meta.object_name
ps-app              | iscan.models.Database.DoesNotExist: Database matching query does not exist.
ps-app              |
ps-app              | During handling of the above exception, another exception occurred:
ps-app              |
ps-app              | Traceback (most recent call last):
ps-app              |   File "/site/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
ps-app              |     response = get_response(request)
ps-app              |   File "/site/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
ps-app              |     response = self.process_exception_by_middleware(e, request)
ps-app              |   File "/site/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
ps-app              |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
ps-app              |   File "/site/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
ps-app              |     return view_func(*args, **kwargs)
ps-app              |   File "/site/env/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
ps-app              |     return self.dispatch(request, *args, **kwargs)
ps-app              |   File "/site/env/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
ps-app              |     response = self.handle_exception(exc)
ps-app              |   File "/site/env/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
ps-app              |     self.raise_uncaught_exception(exc)
ps-app              |   File "/site/env/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
ps-app              |     response = handler(request, *args, **kwargs)
ps-app              |   File "/site/env/src/djangoiscan/iscan/api.py", line 208, in list
ps-app              |     d, _ = models.Database.objects.get_or_create(name=dataset)
ps-app              |   File "/site/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
ps-app              |     return getattr(self.get_queryset(), name)(*args, **kwargs)
ps-app              |   File "/site/env/lib/python3.6/site-packages/django/db/models/query.py", line 541, in get_or_create
ps-app              |     return self._create_object_from_params(kwargs, params)
ps-app              |   File "/site/env/lib/python3.6/site-packages/django/db/models/query.py", line 575, in _create_object_from_params
ps-app              |     obj = self.create(**params)
ps-app              |   File "/site/env/lib/python3.6/site-packages/django/db/models/query.py", line 422, in create
ps-app              |     obj.save(force_insert=True, using=self.db)
ps-app              |   File "/site/env/src/djangoiscan/iscan/models.py", line 401, in save
ps-app              |     self.install()
ps-app              |   File "/site/env/src/djangoiscan/iscan/models.py", line 328, in install
ps-app              |     extract_neo4j(self.name, archive_path)
ps-app              |   File "/site/env/src/djangoiscan/iscan/utils.py", line 57, in extract_neo4j
ps-app              |     shutil.unpack_archive(archive_path, database_directory)
ps-app              |   File "/usr/lib/python3.6/shutil.py", line 977, in unpack_archive
ps-app              |     func(filename, extract_dir, **kwargs)
ps-app              |   File "/usr/lib/python3.6/shutil.py", line 915, in _unpack_tarfile
ps-app              |     tarobj.extractall(extract_dir)
ps-app              |   File "/usr/lib/python3.6/tarfile.py", line 2010, in extractall
ps-app              |     numeric_owner=numeric_owner)
ps-app              |   File "/usr/lib/python3.6/tarfile.py", line 2052, in extract
ps-app              |     numeric_owner=numeric_owner)
ps-app              |   File "/usr/lib/python3.6/tarfile.py", line 2122, in _extract_member
ps-app              |     self.makefile(tarinfo, targetpath)
ps-app              |   File "/usr/lib/python3.6/tarfile.py", line 2171, in makefile
ps-app              |     copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
ps-app              |   File "/usr/lib/python3.6/tarfile.py", line 249, in copyfileobj
ps-app              |     buf = src.read(bufsize)
ps-app              |   File "/usr/lib/python3.6/gzip.py", line 276, in read
ps-app              |     return self._buffer.read(size)
ps-app              |   File "/usr/lib/python3.6/_compression.py", line 68, in readinto
ps-app              |     data = self.read(len(byte_view))
ps-app              |   File "/usr/lib/python3.6/gzip.py", line 482, in read
ps-app              |     raise EOFError("Compressed file ended before the "
ps-app              | EOFError: Compressed file ended before the end-of-stream marker was reached
ps-app              | [08/Apr/2019 15:06:19] "GET /api/corpora/ HTTP/1.1" 500 17957
ps-app              | [08/Apr/2019 15:06:21] "GET / HTTP/1.1" 200 7438
ps-app              | [08/Apr/2019 15:06:21] "GET /api/rest-auth/user/ HTTP/1.1" 200 98
ps-app              | [08/Apr/2019 15:06:21] "GET /api/users/current_user/ HTTP/1.1" 200 103
ps-app              | [08/Apr/2019 15:06:21] "GET /api/corpora/1/ HTTP/1.1" 200 116
ps-app              | /site/env/src/djangoiscan/iscan/models.py:467: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
ps-app              |   conf = yaml.load(f)
ps-app              | [08/Apr/2019 15:06:21] "GET /api/corpora/ HTTP/1.1" 200 238
ps-app              | [08/Apr/2019 15:06:23] "GET /api/corpora/2/ HTTP/1.1" 200 119
ps-app              | [08/Apr/2019 15:06:25] "GET /api/users/current_user/ HTTP/1.1" 200 103
ps-app              | [08/Apr/2019 15:06:25] "GET /api/databases/ HTTP/1.1" 200 234
ps-app              | [08/Apr/2019 15:06:26] "POST /api/databases/8/start/ HTTP/1.1" 200 5
ps-app              | [08/Apr/2019 15:06:26] "GET /api/databases/ HTTP/1.1" 200 234
ps-app              | [08/Apr/2019 15:06:27] "POST /api/databases/8/start/ HTTP/1.1" 200 5
ps-app              | [08/Apr/2019 15:06:27] "GET /api/databases/ HTTP/1.1" 200 234
ps-app              | [08/Apr/2019 15:06:27] "POST /api/databases/8/start/ HTTP/1.1" 200 5
ps-app              | [08/Apr/2019 15:06:27] "GET /api/databases/ HTTP/1.1" 200 234
ps-app              | [08/Apr/2019 15:06:28] "POST /api/databases/8/start/ HTTP/1.1" 200 5
ps-app              | [08/Apr/2019 15:06:28] "GET /api/databases/ HTTP/1.1" 200 234
ps-app              | [08/Apr/2019 15:06:28] "POST /api/databases/8/start/ HTTP/1.1" 200 5
ps-app              | [08/Apr/2019 15:06:28] "GET /api/databases/ HTTP/1.1" 200 234
ps-app              | [08/Apr/2019 15:06:30] "POST /api/databases/8/start/ HTTP/1.1" 200 5
ps-app              | [08/Apr/2019 15:06:30] "GET /api/databases/ HTTP/1.1" 200 234
ps-app              | [08/Apr/2019 15:06:30] "POST /api/databases/8/start/ HTTP/1.1" 200 5
ps-app              | [08/Apr/2019 15:06:30] "GET /api/databases/ HTTP/1.1" 200 234
ps-app              | [08/Apr/2019 15:06:30] "POST /api/databases/8/start/ HTTP/1.1" 200 5
ps-app              | [08/Apr/2019 15:06:30] "GET /api/databases/ HTTP/1.1" 200 234
ps-app              | [08/Apr/2019 15:06:47] "POST /api/databases/8/start/ HTTP/1.1" 200 5
ps-app              | [08/Apr/2019 15:06:47] "GET /api/databases/ HTTP/1.1" 200 234
ps-app              | [08/Apr/2019 15:06:48] "POST /api/databases/8/start/ HTTP/1.1" 200 5
ps-app              | [08/Apr/2019 15:06:48] "GET /api/databases/ HTTP/1.1" 200 234
ps-app              | [08/Apr/2019 15:06:48] "POST /api/databases/8/start/ HTTP/1.1" 200 5
ps-app              | [08/Apr/2019 15:06:48] "GET /api/databases/ HTTP/1.1" 200 234
```

**Comment by msonderegger** [comment]
Any thoughts from you guys?  We can mark this "low priority" since we're not supporting OS X installs for now.
